packages:
  - 'apps/*'
  - 'packages/*'
  - 'database'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  sharp: set this to true or false
  unrs-resolver: true
